### ISSUE TITLE
Linter throws an error in queue.py followed by a FileNotFoundError

### ISSUE THREAD

**Issue by TravelingTechGuy** [SublimeLinter/SublimeLinter-jshint#57]
This started a couple of weeks ago. Nothing changed in my environment, afaik.
System: OSX Yosemite, Node (0.10.34), JSHint 2.5.10 (installed at /opt/local/bin/, and in my path).
Sublime3, SublimeLinter-JSHint, trying to lint a simple JS file:

```
SublimeLinter: -------------------- 
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/Users/ttg/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 58, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ttg/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 66, in loop
    self.lint(view_id, timestamp)
  File "/Users/ttg/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 112, in lint
    self.callback(view_id, timestamp)
  File "/Users/ttg/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 123, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/ttg/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 917, in lint_view
    linter.lint(hit_time)
  File "/Users/ttg/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1301, in lint
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
```

Here's my user settings file:

```
{
    "user": {
        "debug": false,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Danish Royalty/Danish Royalty.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "jshint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "json": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "strict": true
            }
        },
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [
                "/opt/local/bin"
            ],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "php": "html",
            "python django": "python"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
```

**Comment by efolio** [comment]
+1, experiencing the same issue.
And when I save a file, the editor lags like 4-5s, which is VERY annoying.

**Comment by efolio** [comment]
Well, after a little digging, editor lag is due to SublimeLinter, not this plugin.
But I still have this error in my console.

**Comment by CrabDude** [comment]
+1 JSHint stopped working recently, not sure of cause.

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 255, in on_post_save
    callback.on_post_save(v)
  File "/Users/crabdude/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 445, in on_post_save
    self.file_was_saved(view)
  File "/Users/crabdude/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 470, in file_was_saved
    self.lint(vid)
  File "/Users/crabdude/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 123, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/crabdude/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 917, in lint_view
    linter.lint(hit_time)
  File "/Users/crabdude/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1308, in lint
    output = self.run(cmd, self.code)
  File "/Users/crabdude/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1690, in run
    return self.tmpfile(cmd, code)
  File "/Users/crabdude/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1734, in tmpfile
    env=self.env)
  File "/Users/crabdude/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/util.py", line 1278, in tmpfile
    os.remove(path)
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/qq/jdr19x7x4mzg5m14m_9611940000gn/T/SublimeLinter3-crabdude/eventemitter.es6.js'

**Comment by CrabDude** [comment]
Not sure if mine was related, but it turned out the reason jshint was no longer running was that I was using  "View > Syntax > Babel > JavaScript". Switching back to  "View > Syntax > Babel > JavaScriptNext ES6 Syntax" fixed it.

**Comment by st4lk** [comment]
Reinstalling SublimeLinter helps me

**Comment by gregferrell** [comment]
I was having this same issue for a few months. A complete removal and re-install fixed it for me as well. My settings did not get removed so all was ok.

**Comment by ownagedj** [comment]
+1
