### ISSUE TITLE
jshint PATH issues

### ISSUE THREAD

**Issue by narthur157** [SublimeLinter/SublimeLinter-jshint#99]
My jshint executable is at /usr/local/bin/jshint, which is on my PATH. However, this isn't the normal path error. Tried re-installing, and adding the path to user paths.

```Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/Users/myAccount/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 278, in on_activated
    self.check_syntax(view)
  File "/Users/myAccount/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 205, in check_syntax
    Linter.assign(view, reset=True)
  File "/Users/myAccount/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 734, in assign
    if not linter_class.disabled and linter_class.can_lint(syntax):
  File "./python3.3/functools.py", line 251, in wrapper
  File "/Users/myAccount/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1602, in can_lint
    status = 'WARNING: {} deactivated, cannot locate \'{}\''.format(cls.name, executable)
UnboundLocalError: local variable 'executable' referenced before assignment```

**Comment by braver** [comment]
A lot has happened since, we probably did something to fix this by now.
